class CfgVehicles {
	class O_R_Man_Base_F;
	class O_R_Soldier_Base_F: O_R_Man_Base_F
	{
		uniformClass="Aegis_U_O_Luchnik_taiga_F";
	};

	// use correct uniform
	class O_R_Soldier_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_A_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_AAR_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_AMG_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_AMort_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_AHAT_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_AAA_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_AAT_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_AR_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_CBRN_F: O_R_Soldier_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"G_AirPurifyingRespirator_02_olive_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"G_AirPurifyingRespirator_02_olive_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_medic_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Crew_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_F",
			"H_Tank_Black_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_F",
			"H_Tank_Black_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
	};
	class O_R_engineer_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_soldier_exp_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_GL_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_support_gmg_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_support_mg_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_support_mort_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_helicrew_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_CrewHelmetHeli_I_E",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_oli",
			"H_CrewHelmetHeli_I_E",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
	};
	class O_R_helipilot_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_PilotHelmetHeli_O",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_oli",
			"H_PilotHelmetHeli_O",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
	};
	class O_R_Soldier_M_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_AA_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_AT_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Officer_F: O_R_Soldier_Base_F
	{
		uniformClass="Aegis_U_O_Luchnik_officer_taiga_F";
		linkedItems[]=
		{
			"V_Rangemaster_belt_taiga_F",
			"H_Milcap_taiga",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
		respawnLinkedItems[]=
		{
			"V_Rangemaster_belt_taiga_F",
			"H_Milcap_taiga",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
	};
	class O_R_RadioOperator_F: O_R_Soldier_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_Repair_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_LAT_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_HAT_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_lite_F: O_R_Soldier_F
	{
		uniformClass="Aegis_U_O_Luchnik_taiga_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_Milcap_taiga",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_Milcap_taiga",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
	};
	class O_R_Soldier_CQ_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_CQB_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_CQB_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_unarmed_F: O_R_Soldier_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class O_R_Sharpshooter_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_SL_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_TL_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};
	class O_R_Soldier_UAV_F: O_R_Soldier_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"O_UavTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"O_UavTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_grn_F"
		};
	};






	//End of Green/Taiga Uniforms
	//Start of Beige/Arid Uniforms






	class O_R_Soldier_ard_F: O_R_Soldier_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_A_ard_F: O_R_Soldier_A_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_AAR_ard_F: O_R_Soldier_AAR_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_AMG_ard_F: O_R_Soldier_AMG_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_AMort_ard_F: O_R_Soldier_AMort_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_AHAT_ard_F: O_R_Soldier_AHAT_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_AAA_ard_F: O_R_Soldier_AAA_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_AAT_ard_F: O_R_Soldier_AAT_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_AR_ard_F: O_R_Soldier_AR_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_CBRN_ard_F: O_R_Soldier_ard_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"G_AirPurifyingRespirator_02_olive_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"G_AirPurifyingRespirator_02_olive_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_medic_ard_F: O_R_medic_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Crew_ard_F: O_R_Crew_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_arid_F",
			"H_Tank_Black_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_arid_F",
			"H_Tank_Black_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
	};
	class O_R_engineer_ard_F: O_R_engineer_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_soldier_exp_ard_F: O_R_soldier_exp_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_GL_ard_F: O_R_Soldier_GL_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_support_gmg_ard_F: O_R_support_gmg_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_support_mg_ard_F: O_R_support_mg_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_support_mort_ard_F: O_R_support_mort_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_helicrew_ard_F: O_R_helicrew_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_CrewHelmetHeli_I_E",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_oli",
			"H_CrewHelmetHeli_I_E",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
	};
	class O_R_helipilot_ard_F: O_R_helipilot_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"V_TacVest_oli",
			"H_PilotHelmetHeli_O",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_oli",
			"H_PilotHelmetHeli_O",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
	};
	class O_R_Soldier_M_ard_F: O_R_Soldier_M_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_AA_ard_F: O_R_Soldier_AA_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_AT_ard_F: O_R_Soldier_AT_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Officer_ard_F: O_R_Officer_F
	{
		uniformClass="Aegis_U_O_Luchnik_officer_arid_F";
		linkedItems[]=
		{
			"V_Rangemaster_belt_taiga_F",
			"H_Milcap_grn",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
		respawnLinkedItems[]=
		{
			"V_Rangemaster_belt_taiga_F",
			"H_Milcap_grn",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
	};
	class O_R_RadioOperator_ard_F: O_R_Soldier_ard_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_Repair_ard_F: O_R_Soldier_Repair_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_LAT_ard_F: O_R_Soldier_LAT_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_HAT_ard_F: O_R_Soldier_HAT_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_lite_ard_F: O_R_Soldier_lite_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_Milcap_grn",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_Milcap_grn",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
		};
	};
	class O_R_Soldier_CQ_ard_F: O_R_Soldier_CQ_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_CQB_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_CQB_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_unarmed_ard_F: O_R_Soldier_ard_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class O_R_Sharpshooter_ard_F: O_R_Sharpshooter_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_SL_ard_F: O_R_Soldier_SL_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_TL_ard_F: O_R_Soldier_TL_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
	class O_R_Soldier_UAV_ard_F: O_R_Soldier_UAV_F
	{
		uniformClass="Aegis_U_O_Luchnik_arid_F";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_Goggles_Cover_F"
		};
	};
};
